base_frame_id: base_footprint   # or base_link
odom_frame_id: odom
global_frame_id: map

laser_model_type: likelihood_field
laser_max_range: 8.0
laser_min_range: 0.10
laser_z_hit: 0.95
laser_z_short: 0.10
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.20
laser_lambda_short: 0.10
laser_likelihood_max_dist: 2.0

odom_model_type: diff
odom_alpha1: 0.20
odom_alpha2: 0.20
odom_alpha3: 0.20
odom_alpha4: 0.20
odom_alpha5: 0.10

min_particles: 500
max_particles: 3000
kld_err: 0.02
kld_z: 0.99

update_min_d: 0.10
update_min_a: 0.20
resample_interval: 1
transform_tolerance: 0.2

recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

tf_broadcast: true
max_beams: 360
